version: "3.9"

services:

  redis:
    image: redis:alpine
    networks:
      - frontend

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  vote:
    image: jubelshaji/simple_vote_app:vote-latest
    ports:
      - 80:80
    networks:
      - frontend
    deploy:
      replicas: 2

  result:
    image: jubelshaji/simple_vote_app:result-latest
    ports:
      - 81:80
    networks:
      - backend

  worker:
    image: jubelshaji/simple_vote_app:worker-latest
    networks:
      - frontend
      - backend
    deploy:
      replicas: 2

networks:
  frontend:
  backend:

volumes:
  db-data: